export const GET_DECISION = 'GET_DECISION'
export const SET_DECISION = 'SET_DECISION'

export const HANDLE_DECISION = 'HANDLE_DECISION'
export const ADD_IMPRESSION = 'ADD_IMPRESSION'
export const CLEAR_DECISION = 'CLEAR_DECISION'
