export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'

export const GET_INITIAL_CONFIG = 'GET_INITIAL_CONFIG'
export const SET_INITIAL_CONFIG = 'SET_INITIAL_CONFIG'
